---
- name: Launch Workflow
  hosts: localhost
  connection: local
  tasks:
    - name: Get all the hosts matching with the pattern
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - "{{ region }}"
      register: "hosts"



    - name: Launch a Update workflow
      tower_workflow_launch:
        workflow_template: "Refresh_Templates_Workflow✅"
        limit: "{{ item.item }}"
        wait: true
      with_items: "{{hosts.results}}"

