---
- name: Launch Workflow
  hosts: localhost
  connection: local
  tasks:
    - name: show all the hosts matching the pattern, i.e. all but the group www
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - emea
      register: "r"

    - name: show all the hosts matching the pattern, i.e. all but the group www
      ansible.builtin.debug:
        msg: "{{ r }}"
      


    - name: Launch a workflow with a timeout of 10 seconds
      tower_workflow_launch:
        workflow_template: "Refresh_Templates_Workflow_EMEA✅"
        limit: "{{ item }}"
        wait: true
      with_items: "{{r.stdout}}"
    #  loop:
     #   - Gold-CentOS7_FR
      #  - Gold-CentOS8_FR
       # - Gold-ubuntu18.04_FR

