---
- name: Launch Workflow
  hosts: localhost
  connection: local
  tasks:
    - name: Launch a workflow with a timeout of 10 seconds
      tower_workflow_launch:
        workflow_template: "Refresh_Templates_Workflow_EMEA✅"
        limit: emea
        wait: true

